inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Строгие проверки
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true # Неиспользуемые переменные

Rails/ApplicationController:
  Enabled: true # Наследование от ApplicationController

# Жёсткие проверки методов
Lint/UnderscorePrefixedVariableName:
  Enabled: true

Lint/MissingSuper:
  Enabled: true # Пропущен super в initialize
