source "https://rubygems.org"

gem "rails", "~> 8.0.2"
gem "pg", "~> 1.5", ">= 1.5.9"
gem "puma", ">= 5.0"
gem "solid_cache"
gem "solid_queue"

gem "bootsnap", require: false
gem "kamal", require: false

gem "rack-cors", "~> 2.0", ">= 2.0.2" #

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "brakeman", require: false
  gem "dotenv", "~> 3.1", ">= 3.1.7"
end

group :test do
  gem "rspec-rails", "~> 7.1", ">= 7.1.1"
  gem "factory_bot_rails", "~> 6.4", ">= 6.4.4"
  gem "database_cleaner-active_record", "~> 2.2", ">= 2.2.0"
  gem "shoulda-matchers", "~> 6.4"
  gem "faker", "~> 3.5", ">= 3.5.1"
end
